server:
  servlet:
    context-path: /Study_Group

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/studygroup #jdbc:h2:tcp://localhost/~/wpl2021f
    username: root #sa
    password: Choi123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  devtools:
    livereload:
      enabled: true
---
spring:
  config:
    import: application-oauth2.yml